/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "/cut": "/割草",
    "Auto: OFF": "自动：关闭",
    "Automation Upgrades": "自动化升级",
    "Buy 1": "购买 1",
    "Buy All": "购买全部",
    "Buy Max": "购买最大",
    "Cancel": "取消",
    "Click any challenge to start! Click again to exit.": "点击任何挑战开始！再次单击退出。",
    "Crystal Upgrades": "水晶升级",
    "Crystallize": "结晶",
    "Crystallizing resets everything prestige as well except Platinum for Crystals.": "结晶也会重置所有声望，除了水晶的铂金。",
    "Effect:": "影响：",
    "Endgame: Level 370, Tier 24, 7 Grasshop": "残局：370 级、24 级、7 级草场",
    "every completions.": "每个完成。",
    "every grasshop.": "每一个草场。",
    "every grasshop. Keep Prestige challenges on Grasshop.": "每一个草场。在 草场 上保持声望挑战。",
    "every grasshop. Unlock more automation upgrades.": "每一个草场。解锁更多自动化升级。",
    "Gain": "获得",
    "Gain more Crystals based on your tier and PP.": "根据您的等级和 PP 获得更多水晶。",
    "Gain more PP based on your level and grass.": "根据你的等级和草获得更多的 PP。",
    "Goal: ???": "目标： ？？？",
    "Grass Cutting Incremental": "割草增量",
    "Grass Upgrades": "草升级",
    "Grasshop": "草场",
    "Grasshop once to unlock.": "草场 一次解锁。",
    "Grasshop!": "草场！",
    "Grasshopping resets everything crystalize does as well as crystals, crystal upgrades, challenges.": "草场重置一切结晶以及水晶，水晶升级，挑战。",
    "Grassless": "无草",
    "Hard Reset": "硬重置",
    "Hide upgrades which is maxed/purchased:": "隐藏已最大化/购买的升级：",
    "Inactive": "不活跃",
    "Join Discord Server": "加入 Discord 服务器",
    "Keep Crystallize challenges on Grasshop.": "在 草场 上保留 结晶 挑战。\n",
    "Less Level": "更少的等级",
    "Level": "等级",
    "more grass. Grass gain is increased by": "更多的草。草增益增加",
    "more TP. TP gain is increased by": "更多的TP。 TP 增益增加",
    "more XP. XP gain is increased by": "更多经验值。 XP增益增加",
    "No Tiers": "无等级",
    "per completion.": "每次完成。",
    "per grasshop (start at 3). Unlock more automation upgrades.": "每个草场（从 3 开始）。解锁更多自动化升级。",
    "Perk Upgrades": "天赋升级",
    "Platinum Chance": "白金几率",
    "Platinum Upgrades": "白金升级",
    "Platinum worth": "白金价值",
    "Prestige": "声望",
    "Prestige Upgrades": "声望升级",
    "Prestigeless": "没有声望",
    "Prestiging resets your grass, grass upgrades, level and perks for Prestige Points (PP).": "声望会重置你的草、草升级、等级和天赋对于声望点 (PP)。",
    "Reach Level 200 to unlock": "达到200级解锁",
    "Really Grass Cutting Incremental - Prototype v0.3 - Made by MrRedShark77": "真正的割草增量 - Prototype v0.3 - 由 MrRedShark77 制作",
    "Reduced Resources": "减少资源",
    "Reward: Grass gain is increased by": "奖励：草增益增加",
    "Reward: Grass multiplier's exponent is increased by": "奖励：草乘数的指数增加",
    "Reward: PP gain is increased by": "奖励：PP增益增加",
    "Reward: TP gain is increased by": "奖励：TP增益增加",
    "Reward: XP gain is increased by": "奖励：经验增益增加",
    "Status:": "地位：",
    "The game inspired by": "游戏灵感来自",
    "The Level requirement is expensive.": "级别要求很昂贵。",
    "Tier": "等级",
    "times": "次",
    "Warning! Recommended size is 1920x1080! You may change zoom!": "警告！推荐尺寸为1920x1080！您可以更改缩放！",
    "You cannot buy any grass upgrades.": "您不能购买任何草升级。",
    "You cannot buy any Prestige Upgrades.": "您不能购买任何声望升级。",
    "You cannot tier up.": "你不能提升层级。",
    "You have grasshopped": "你有草场",
    "Prestige once to unlock.": "声望一次以解锁。",
    "Reach Level 30 to Prestige.": "达到声望等级 30。",
    "argh": "啊啊",
    "^0.5 to Grass, XP & PP gain.": "^0.5 草、经验 和 声望点 增益。",
    "Reach Level 5 to unlock.": "达到5级以解锁。",
    "doubled": "翻倍",
    "every": "每个",
    "Grass Value": "草价值",
    "Grow Speed": "成长速度",
    "Increase experience (XP) gained by": "增加获得的经验（XP）",
    "Increase grass cap by": "增加草上限",
    "Increase grass cut range by": "将割草范围增加",
    "Increase Grass gain by": "增加草增益",
    "Increase grass grow speed by": "将草的生长速度提高",
    "levels.": "等级。",
    "More Grass": "更多的草",
    "per level.": "每级。",
    "per level. Base is 50.": "每级。 基数为 50。",
    "Range": "范围",
    "This effect is": "这个效果是",
    "XP": "经验值",
    "Grow Amount Perk": "生长数量天赋",
    "Grow Speed Perk": "成长速度天赋",
    "Increase the grass grow amount by": "将草的生长量增加",
    "Increase XP gain by": "增加经验增益",
    "per level multiplied by experience level.": "每个等级乘以经验等级。",
    "Range Perk": "范围天赋",
    "Value Perk": "价值天赋",
    "XP Perk": "经验天赋",
    "Cap Perk": "上限天赋",
    "Auto cuts grass every": "自动割草每",
    "Autocut": "自动割草",
    "seconds (-1s every level after the first).": "秒（第1级之后的每个等级 -1 秒）。",
    "Maxed": "最大",
    "Auto cuts grass is worth": "自动割草值得",
    "Autocut Amount": "自动割草数量",
    "Autocut Value": "自动割草",
    "Grass Upgrade Autobuy": "草升级自动购买",
    "Increases auto cut amount by": "将自动割草数量增加",
    "more grass, XP & TP.": "更多的草，经验和TP。",
    "Perk Save P": "天赋保存 P",
    "Reach Tier 3 to unlock.": "达到第 3 层即可解锁。",
    "Decreases auto cut time by": "将自动切割时间减少",
    "Increase grass gain by": "增加草增益",
    "Plat Grass": "白金草",
    "Plat XP": "白金经验",
    "seconds per level.": "秒每级。",
    "Starter AC": "起动机交流电",
    "Crystallize once to unlock.": "结晶一次即可解锁。",
    "for every": "对于每个",
    "Grass Value II": "草价值 II",
    "Increase Tier Points (TP) gain by": "将层级点数 (TP) 增益提高",
    "levels": "等级",
    "per level. This effect is": "每级。 这个效果是",
    "per level. This effect is increased by": "每级。 这个效果增加了",
    "Prestige Points": "声望点",
    "Reach Level 100 to Crystallize.": "达到 100 级即可结晶。",
    "Anti-Grass Upgrades": "反草升级",
    "Assembler": "汇编器",
    "Best Charge Milestones:": "最佳充能里程碑：",
    "Challengerism": "挑战者主义",
    "Charge rate is increased by": "充能率增加",
    "Charger charge bonuses increase": "充能器充能奖励增加",
    "Charger charge bonuses increase another": "充能器充能奖励增加另一个",
    "Crystalless": "无晶体",
    "Decelerate": "减速",
    "Decelerating will temporarily slow down time and reduce the effectiveness of everything significantly until you press the Accelerate button.": "减速会暂时减慢时间并显着降低一切的有效性，直到您按下加速按钮。",
    "Decelerator": "减速器",
    "During this time you will not be able to earn regular grass, Instead you earn anti-grass which is spent in Anti-grass upgrades panel which takes the place of regular Grass Upgrades panel.\n    These upgrades affect the normal realm.": "在此期间，您将无法获得普通草，而是获得用于代替普通草升级面板的反草升级面板中的反草。\n这些升级会影响正常领域。",
    "Endgame: Level 850, Tier 64, 34 Grasshop; Level 30 in Anti-Realm": "残局：850级，64级，34级草场；反境界30级",
    "Foundry": "铸造厂",
    "Gain more Steels based on grasshop and Crystal.": "获得更多基于草和水晶的钢铁。",
    "Generator": "发电机",
    "However, and level scales instantly.": "但是，级别会立即扩展。",
    "OoM (order of magnitude) sooner.": "OoM（数量级）更快。\n",
    "OoM sooner per grasshop starting at 24.": "从 24 点开始，每个草场的 OoM 会更快。",
    "OoM sooner. Grasshop animation will no longer play.": "OoM 越快越好。 草场 动画将不再播放。\n",
    "Really Grass Cutting Incremental - Prototype v0.3.2 - Made by MrRedShark77": "真正的割草增量 - Prototype v0.3.2 - Made by MrRedShark77",
    "Reduced Resources II": "减少资源 II",
    "Reset everything grasshop does, but it benefits from the milestones for grasshop.": "重置 草场 所做的一切，但它受益于 草场 的里程碑。",
    "Reward: Charge rate is increased by": "奖励：充能率增加",
    "Reward: Crystal gain is increased by": "奖励：水晶增益增加",
    "Reward: Grass effect's exponent is increased by": "奖励：草效果指数增加",
    "Reward: Steel gain is increased by": "奖励：钢铁增益增加",
    "Steelie": "Steelie",
    "Steelie!": "Steelie！",
    "The Factory": "工厂",
    "Tier multiplier's exponent is increased by": "层乘数的指数增加了",
    "Unlock Steelie reset. Grasshop does not reset perks.": "解锁 Steelie 重置。 草场 不会重置特权。\n",
    "Unlock two more generator upgrades related to charge.": "解锁另外两个与充能相关的发电机升级。\n",
    "You are trapped in Prestige & Crystal Challenges (except Reduced Resources).": "您被困在声望和水晶挑战中（资源减少除外）。",
    "You cannot buy any Crystal Upgrades.": "您不能购买任何水晶升级。",
    "Reach Level 1 to unlock.": "达到 1 级即可解锁。",
    "Auto: ON": "自动: 开启",
    "Crystals": "水晶",
    "Grass Value III": "草价值 III",
    "Increase PP gain by": "提高 PP 增益",
    "Reach Level": "达到等级",
    "Steel": "钢",
    "Unlock a building (on bottom of Factory) where you can slow down time. Each level increases charge rate by": "解锁一座建筑（位于工厂底部），您可以在其中放慢时间。 每个级别增加充能率",
    "to Grasshop": "到草场",
    "Crystal Charge": "水晶充能",
    "Increase charge rate by": "将充能率提高",
    "Increase steel gain by": "增加钢增益",
    "Steel Prestige": "钢声望",
    "Temp. Charge:": "Temp. 充能：",
    "to PP/Crystal generator multiplier from factory upgrade": "从工厂升级到 PP/水晶生成器乘数",
    "to Steel multiplier based on time since last steelie (max 1 hour)": "到 钢 乘数基于自上次 Steelie 以来的时间（最多 1 小时）",
    "Best Charge:": "最佳充能：",
    "(softcapped)": "(软上限了)",
    "Anonymity": "匿名",
    "Anonymity resets your anti-grass, anti-grass upgrades, level for Anonymity Points (AP).": "匿名会重置您的反草、反草升级、匿名点数 (AP) 级别。",
    "Anonymity Upgrades": "匿名升级",
    "Buy Next": "购买下一个",
    "Crystal Perk": "水晶天赋",
    "Decelerating will force a Steelie.": "减速将迫使 Steelie。",
    "Endgame: Level 950, Tier 75, 37 Grasshop; Level 100 in Anti-Realm": "残局：950级、75级、37级草场； 反境界100级",
    "Gain more AP based on your level and anti-grass.": "根据您的等级和防草获得更多 AP。",
    "Grass Value III, XP III, TP II & PP": "草价值 III、XP III、TP II 和 PP",
    "Increase AP gain by": "增加AP增益",
    "Increase Crystal gain by": "增加水晶增益",
    "Increase Crystal multiplier's exponent by": "将水晶乘数的指数增加",
    "Increase PP multiplier's exponent by": "将 PP 乘数的指数增加",
    "Increase TP gain by": "增加 TP 增益",
    "Limitless Crystal Upgrades": "无限水晶升级",
    "Limitless Crystal Upgrades II": "无限水晶升级 II",
    "Limitless Grass Upgrades": "无限草升级",
    "Limitless Grass Upgrades II": "无限草升级 II",
    "Limitless Prestige Upgrades": "无限声望升级",
    "Plat Anonymity": "平台匿名",
    "Plat PP": "平台 PP",
    "Plat-Exponential PP": "平台指数 PP",
    "PP Perk": "PP天赋",
    "Prestige Upgrades will no longer have maximum limit.": "声望升级将不再有最大限制。",
    "Really Grass Cutting Incremental - Prototype v0.3.3 - Made by MrRedShark77": "真正的割草增量 - Prototype v0.3.3 - 由 MrRedShark77 制作",
    "Crystal Generation": "水晶生成",
    "passive Crystal generation per level.": "每级被动水晶生成。",
    "passive PP generation per level.": "每级被动 PP 生成。",
    "PP Generation": "PP 生成",
    "Prestige Charge": "声望充能",
    "Charger": "充电器",
    "Unlock a building (on bottom of Factory) where you can unscale anything. Each level increases charge rate by": "解锁一座建筑物（位于工厂底部），您可以在其中取消缩放任何东西。 每个级别增加充能",
    "Unlock a building (on right of Factory) where you can boost production multipliers with charge. Each level increases charge rate by": "解锁一座建筑物（位于工厂右侧），您可以在其中通过充能提高产量倍数。 每个级别增加充能率",
    "Unlock a building (on right of Factory) where you can upgrade prestige/crystal generation. Each level increases generator's effect by": "解锁一座建筑物（在工厂右侧），您可以在其中升级声望/水晶生成。 每级增加发电机的效果",
    "Unlock a building (on right of Factory) where you can upgrade steel production. Each level increases foundry's effect by": "解锁可以升级钢铁生产的建筑物（位于工厂右侧）。 每个级别都会增加铸造厂的效果",
    "Create Rocket Part": "制作火箭零件",
    "Charge": "充能",
    "Craft to ??? Rocket Fuel": "制作 ??? 火箭燃料",
    "Endgame: Level 1400, Tier 100, 47 Grasshop; Level 400 in Anti-Realm": "残局：1400 等级，100 层级，47 草场； 反境界 400级",
    "Gain more Oil based on your tier and AP.": "根据您的等级和 AP 获得更多石油。",
    "Liquefy": "液化",
    "Liquefy resets everything Anonymity as well as your AP, Anonymity upgrades & tier for Oil.": "液化重置一切匿名以及你的 AP、匿名升级和石油等级。",
    "Momentum Upgrades": "动力升级",
    "Next Rocket Fuel:": "下一个火箭燃料：",
    "Oil": "油",
    "Oil Upgrades": "石油升级",
    "Really Grass Cutting Incremental - Prototype v0.3.6 - Made by MrRedShark77": "真正的割草增量 - Prototype v0.3.6 - Made by MrRedShark77",
    "Refinery": "炼油厂",
    "Reset everything liquefy does as well as oil, oil upgrades, steel and total rocket fuel.\n    You will create a rocket part, earn one momentum, and reset the cost to make rocket fuel.\n    You keep rocket fuel and rocket fuel upgrades.": "重置 liquefy 所做的一切以及石油、石油升级、钢铁和总火箭燃料。\n 你将创建一个火箭部件，获得一个动力，并重置制造火箭燃料的成本。\n 你保留火箭燃料和火箭燃料升级 .",
    "Rocket Fuel Upgrade": "火箭燃料升级",
    "Rocket Part": "火箭零件",
    "??? Stars": "??? 星星",
    "Astral": "星界",
    "Automatically update best anonymity/liquefy with current values if they are higher (while decelerated).": "如果当前值较高（减速时），则使用当前值自动更新最佳匿名/液化。\n",
    "Automation Tree": "自动化树",
    "Endgame: Level 2500+, Tier 250+; Level 600+ in Anti-Realm; 15+ Grass-skip": "残局：2500+级，250+级；逆境600级以上； 15+ 跳草",
    "every astral.": "每个星体。",
    "First galactic breaks rocket part's limit.": "第一个银河突破火箭部分的极限。",
    "Fundry": "基金会",
    "Funify": "有趣",
    "Funify!": "有趣！",
    "Gain more Fun based on grass-skip and oil.": "基于草跳和油获得更多乐趣。",
    "Gain more Stars based on rocket parts, starting at 10.": "根据火箭部件获得更多星星，从 10 开始。",
    "Galactic": "银河",
    "Go Galaxy!": "去银河！",
    "Go to Space": "去太空",
    "Grass gain is increased by": "草增益增加",
    "Grass-Skip": "草跳",
    "Grass-skip once to unlock.": "草跳一次解锁。",
    "Grass-Skip!": "草-跳过！",
    "Grass-skipping resets everything liquefy does as well as oil except oil upgrades.": "除油升级外，跳草会重置液化和油的所有功能。",
    "Keep challenges on Grasshop, Galactic.": "继续挑战 草场，银河。",
    "Moonstone Upgrades": "月光石升级",
    "more moonstones per 2 grass-skips (starting at 8).": "每 2 个草跳（从 8 个开始）有更多的月光石。",
    "more platinum and SP. Active sixth 7 grasshop milestones if you haven't reached them.": "更多的铂金和SP。如果您还没有达到它们，则激活第六个 7 个草场里程碑。\n",
    "more SP per grass-skip.": "每个草跳过更多的SP。",
    "more stars per grass-skip.": "每个草跳更多的星星。",
    "Multi-Grasshop:": "批量草场：",
    "per astral.": "每个星体。",
    "Progession Tree": "进度树",
    "Really Grass Cutting Incremental - v0.4.1 - Made by MrRedShark77": "真正的割草增量 - v0.4.1 - 由 MrRedShark77 制作",
    "Reset EVERYTHING except rocket fuel upgrades.": "重置除了火箭燃料升级之外的一切。",
    "Reset everything grass-skip does, but it benefits from the milestones for grass-skip.": "重置草地跳跃所做的一切，但它受益于草地跳跃的里程碑。",
    "SFRGT gain is increased by": "SFRGT 增益增加",
    "Speed Tree": "速度树",
    "Star gain is increased by": "星级增益增加",
    "Stars": "星星",
    "Super Fun Real Good Time Generator": "超级有趣的实时好时光发生器",
    "The Funny Machine": "有趣的机器",
    "Tier requirement is sightly weaker.": "等级要求略弱。",
    "TP gain is increased by": "TP 增益增加",
    "Unlock Funify reset and The Funny Upgrade rocket fuel upgrade.": "解锁 Funify 重置和有趣的升级火箭燃料升级。\n",
    "XP gain is increased by": "XP增益增加",
    "You have grass-skipped": "你已经跳过草了",
    "Your lowest grasshop is": "你最低的草皮是",
    "(on left of Star Chart).": "（星图左侧）。\n",
    "Active sixth 7 grasshop milestones if you haven't reached them.": "如果您还没有达到它们，则激活第六个 7 个草场里程碑。\n",
    "Dark Matter Plant": "暗物质植物",
    "Double": "双倍的",
    "Endgame: Level 4200+, Tier 420+; Level 1300+ in Anti-Realm; 30+ Grass-skip; AGHGS 25+": "残局：4200+级，420+级；反境界1300+级； 30+ 跳草； AGHGS 25+",
    "every grass-skip.": "每个草跳。",
    "every zero grasshop grass-skips.": "每零个蚂蚱草跳。",
    "First sacrifice unlocks new the funny machine upgrade.": "第一次牺牲解锁新的有趣的机器升级。",
    "Gain more Dark Matters based on your stars (starting at 1 Qt) and astral (starting at 45).": "根据你的星星（从 1 Qt 开始）和星界（从 45 开始）获得更多暗物质。",
    "Galactic no longer reset Steelie time.": "银河不再重置 Steelie 时间。\n",
    "Increase Fun gained by": "增加获得的乐趣",
    "Increase SP gained by": "增加SP增益",
    "is": "是",
    "Keep momentum and momentum upgrades on galactic.": "保持银河的动量和动量升级。",
    "lowest grasshop": "最低的蚂蚱",
    "moonstone earned and its chance.": "月光石获得和它的机会。\n",
    "more platinum and SP.": "更多的铂金和SP。",
    "Multi-Gras-skip:": "批量草跳：",
    "OoM sooner per grassskip.": "OoM 越快每个草跳。",
    "Raise SP gain of the": "提高SP增益",
    "Really Grass Cutting Incremental - v0.4.1.3 - Made by MrRedShark77": "真正的割草增量 - v0.4.1.3 - 由 MrRedShark77 制作",
    "Sacrifice": "牺牲",
    "Sacrifice forces a Galactic reset as well as resetting Astral, Stars, Fun, Fun Upgrades (excluding ones in The Funny Machine) and SFRGT to earn Dark Matter.": "牺牲迫使银河重置以及重置 Astral、Stars、Fun、Fun 升级（不包括 The Funny Machine 中的升级）和 SFRGT 以获得暗物质。",
    "SFRGT is increased by": "SFRGT 增加",
    "Steel is increased by": "钢增加",
    "Steelie no longer reset its time.": "Steelie 不再重置时间。",
    "th power.": "权力。",
    "Unlock a new rocket fuel for stars.": "为恒星解锁一种新的火箭燃料。",
    "Unlock milestones below grasshop 0.": "解锁 草场 0 以下的里程碑。\n",
    "Unlock more momentum upgrades, one moonstone upgrade.": "解锁更多动力升级，一个月光石升级。\n",
    "Unlock the": "解锁",
    "You don't lose platinum on galactic.": "你不会在银河系失去铂金。",
    "Your": "您的",
    "Allow grasshopping multiple times. (change in options)\n        ": "允许多次草场。 （选项更改）\n",
    "Autocut value applies to": "自动切割值适用于",
    "Autocut Value Platinum": "自动切割价值白金",
    "Automation Keeper": "自动化守护者",
    "Divide the time to max foundry bonus by": "将达到最大铸造奖金的时间除以",
    "Faster Foundry": "更快的铸造厂",
    "Go to Ground": "去地面",
    "Increase auto cut amount by": "将自动切割量增加",
    "Increase Crystal base from tier from": "从层级增加水晶基础",
    "Increase platinum gain by": "增加铂金收益",
    "Increase Platinum gain by": "增加铂金收益",
    "Increase PP base from level from": "从等级增加PP基础",
    "Increase SP (Space Power) gained by": "增加获得的SP（空间力量）",
    "Increase stars gain by": "增加星星增益",
    "Increase Steel gain by": "增加钢铁增益",
    "Increases charge rate by": "将充电率提高",
    "Keep all automation upgrades on Galactic.": "保留 Galactic 上的所有自动化升级。",
    "Moon Platinum": "月亮铂金",
    "Moon Star": "月亮星星",
    "Moon TP": "月亮TP",
    "Moon XP": "月亮经验值",
    "Multi Grasshop": "批量草场",
    "platinum": "铂",
    "Space Power": "空间力量",
    "Stellar ACS": "恒星 ACS",
    "Stellar Autocut": "恒星自动切割",
    "Stellar Charger": "恒星充电器",
    "Stellar Grass Cap": "恒星草上限",
    "The Factory Automation": "工厂自动化",
    "to": "至",
    "Unlock more upgrades.": "解锁更多升级。",
    "Unlock Steel Generation upgrade at max level.": "在最高级别解锁钢铁世代升级。",
    "You can now automatically buy the Factory upgrades.\n        ": "您现在可以自动购买工厂升级。\n",
    "Increase Oil gain by": "加石油增益",
    "Increase XP multiplier's exponent by": "将 XP 乘数的指数增加",
    "per level, but only in normal realm.": "每级，但仅限于普通领域。",
    "Plat-Exponential XP": "白金指数 XP",
    "Platinum Oil": "白金石油",
    "Progress": "进度",
    "Anti-Grass Upgrades Autobuy": "反草升级自动购买",
    "Crystal Upgrade Autobuy": "水晶升级自动购买",
    "Crystal Upgrades EL": "水晶升级 EL",
    "Crystal Upgrades no longer spend crystal.": "水晶升级不再消耗水晶。",
    "Grass Upgrades EL": "草升级 EL",
    "Grass Upgrades no longer spend grass.": "草升级不再消耗草。",
    "Grow Amount": "增长量",
    "Increase grass grow amount by": "将草的生长量增加",
    "Increase multiplier's base from Tier by": "将乘数的基数从层级增加",
    "Keep perks on Crystallize.": "保持对结晶的好处。",
    "of crystal you would earn on crystallize per second.": "水晶，您将获得每秒结晶。",
    "of PP you would earn on prestige per second.": "PP 你将获得的声望每秒。",
    "Oil Drilling Rig": "石油钻机",
    "Passively generate": "被动生成",
    "Passively generate oil and AP slowly based off your best Liquefy/Anonymity per level. Each level increases charge rate by": "根据每个级别的最佳液化/匿名性，被动地产生石油和 AP。每个级别增加充电率",
    "per level. Starting base is": "每个级别。起始基地是",
    "Perk Autobuy": "天赋自动购买",
    "Perk Save C": "天赋保存 C",
    "Prestige Upgrade Autobuy": "声望升级自动购买",
    "Prestige Upgrades EL": "声望升级 EL",
    "Prestige Upgrades no longer spend PP.": "声望升级不再消耗 PP。",
    "Rocket Launch Pad": "火箭发射台",
    "Tier Base": "等级基础",
    "Unlock a building (on bottom of Factory) where you can convert charge and oil into rocket fuel. Each level increases charge rate by": "解锁一座建筑物（位于工厂底部），您可以在其中将电荷和石油转化为火箭燃料。每个级别增加充电率",
    "Unlock a building (on right of Factory) where you can unscale anything. Each level increases charge rate by": "解锁一座建筑（在工厂右侧），您可以在其中取消缩放任何东西。每个级别增加充电率",
    "Unlock a building (on top of Factory) where you can build a rocket. Each level increases charge rate by": "解锁可以建造火箭的建筑物（位于工厂顶部）。每个级别增加充电率",
    "will no longer have maximum limit.": "将不再有最大限制。",
    "You can now automatically buy Anti-Grass Upgrades.": "您现在可以自动购买防草升级。",
    "You can now automatically buy Crystal Upgrades.": "您现在可以自动购买水晶升级。",
    "You can now automatically buy Perk Upgrades.": "您现在可以自动购买 天赋 升级。",
    "You can now automatically buy Prestige Upgrades.": "您现在可以自动购买声望升级。",
    "Dark Matter Upgrades": "暗物质升级",
    "Multi-Grass-skip:": "批量草跳：",
    "Endgame: Level 4500+, Tier 480+; Level 1400+ in Anti-Realm; 32+ Grass-skip; AGHGS 25+": "残局：4500+级，480+级； 反境界1400+； 32+ 草跳； AGHGS 25+",
    "Really Grass Cutting Incremental - v0.4.3.1 - Made by MrRedShark77": "真正的割草增量 - v0.4.3.1 - 由 MrRedShark77 制作",
    "During this time you will not be able to earn regular grass, Instead you earn unnatural grass which is spent in unnatural grass upgrades panel which takes the place of regular Grass Upgrades panel.\n    These upgrades affect the normal and anti realm, are kept on galactic/sacrifice.": "在此期间，您将无法获得普通草，而是获得非自然草，这些草用于非自然草升级面板，取代常规草升级面板。\n 这些升级影响正常和反领域，保持开启 银河/牺牲。",
    "Dark Matter": "暗物质",
    "Endgame: Level 6000+, Tier 740+; Level 80+ in Unnatural Realm; 37+ Grass-skip; AGHGS 32+": "残局：等级 6000+，等级 740+； 非自然领域80级以上； 37+跳草； AGHGS 32+",
    "Experience": "经验",
    "First sacrifice unlocks new the funny machine upgrade and moonstone upgrade.": "第一次献祭解锁新的搞笑机器升级和月光石升级。",
    "Fun": "乐趣",
    "Gain more NP based on your level and unnatural grass.": "根据您的等级和非天然草地获得更多 NP。",
    "Grass": "草",
    "Increase momentum gain by": "增加动量增益",
    "momentum, and reset the cost to make rocket fuel.\n    You keep rocket fuel and rocket fuel upgrades.": "势头，并重置制造火箭燃料的成本。\n 你保持火箭燃料和火箭燃料升级。",
    "Moonstone": "月长石",
    "Normality": "常态",
    "Normality resets your unnatural grass, unnatural grass upgrades, level, charge and astral for Normality Points (NP).": "常态会重置您的非自然草地、非自然草地升级、等级、冲锋和常态点数 (NP) 的星体。",
    "Normality Upgrades": "常态升级",
    "per 8 astral.": "每 8 个星体。",
    "Platinum": "铂",
    "Recelerate": "加速",
    "Recelerating will temporarily slow down time and reduce the effectiveness of everything significantly until you press the Accelerate button.": "减速会暂时减慢时间并显着降低一切的有效性，直到您按下加速按钮。",
    "Recelerator": "减速器",
    "Reset everything liquefy does as well as oil, oil upgrades, steel and total rocket fuel.\n    You will create a rocket part, earn": "重置液化所做的一切，以及石油、石油升级、钢铁和总火箭燃料。\n你将创造一个火箭零件，赚取",
    "SFRGT": "SFRGT",
    "Unlock more dark matter upgrades.": "解锁更多暗物质升级。",
    "Unnatural Grass Upgrades": "非自然草升级",
    "\n    To do an astral prestige, you must reach Astral 100.": "\n 要获得星界声望，您必须达到星界 100。",
    "(aka. Astral Prestige, on top of star chart) and": "（又名。Astral Prestige，在星图顶部）和",
    "as stronger.": "作为更强。",
    "Astral Prestige": "星光声望",
    "Astro": "天文",
    "Astro Upgrades": "天文升级",
    "Astrolabe": "星盘",
    "Auto Grasshop & Grass-skip no longer reset anything.": "Auto Grasshop & Grass-skip 不再重置任何东西。",
    "Cloud": "云",
    "Cloud Upgrades": "云升级",
    "Compaction works": "压实工程",
    "Cosmic": "宇宙的",
    "Do Astral Prestige": "做星光声望",
    "Doing an astral prestige will reset your astral back to 0 but will significantly increase the power of the astral bonuses.": "进行星体声望会将您的星体重置为 0，但会显着增加星体奖励的力量。",
    "Each astral prestige done will increase the base SP requirement as well as the requirement scaling.": "完成的每个星体声望都会增加基本 SP 要求以及要求缩放。",
    "Endgame: Level 16,000+; Astral Prestige 2; Grass Jump 5+; Planetary Tier 9+;": "残局：等级 16,000+； 星界声望 2； 草地跳跃 5+； 行星等级 9+；",
    "Enter the Planetoid": "进入小行星",
    "Form Ring": "成型环",
    "Form the Ring": "组成环",
    "Gain more Astro based on your level and planetarium.": "根据您的等级和天文馆获得更多 天文。",
    "Gain more Measures based on your level and astro.": "根据您的等级和天文获得更多测量。",
    "Gain more Planets based on your level and measure.": "根据您的等级和测量获得更多行星。",
    "Gain more rings based on your level and planetarium (starting at 1.000 B).": "根据您的等级和天文馆获得更多环（从 1.000 B 开始）。",
    "Gain more XP based on planetary tier.": "根据行星等级获得更多 XP。",
    "Go Planetary": "去行星",
    "Grass Jump": "跳草",
    "Grass-Jump": "跳草",
    "Grass-Jump once to unlock.": "跳草一次解锁。",
    "Grass-Jump!": "跳草！",
    "Grass-jumping resets everything normality does as well as cloud, cloud upgrades.": "跳草重置一切常态以及云，云升级。",
    "in Unnatural Realm.": "在非自然领域。",
    "Increase Dark Matter gained by": "增加获得的暗物质",
    "Increase Momentum gained by": "增加获得的动力",
    "Measure": "测量",
    "Measure Upgrades": "测量升级",
    "Momentum gain is increased based on rocket part at a reduced rate.": "动量增益基于火箭部件以降低的速率增加。",
    "more Astro and Measure per planetary tier.": "每个行星层都有更多天文和测量。",
    "more Planetarium and Cosmic per planetary tier.": "每个行星层都有更多的天文馆和宇宙。",
    "Observatorium": "天文台",
    "per grass-jump.": "每次跳草。",
    "Planet Upgrades": "行星升级",
    "Planetarium": "天文馆",
    "Planetarium Upgrades": "天文馆升级",
    "Planetary": "行星的",
    "Planetoid": "小行星",
    "Planets": "行星",
    "power.": "力量。",
    "Quadrant": "象限",
    "Really Grass Cutting Incremental - v0.4.4.1 - Made by MrRedShark77": "真正的割草增量 - v0.4.4.1 - MrRedShark77 制作",
    "Reduce XP penalty in": "减少 XP 惩罚",
    "Reservatorium Tree": "储存树",
    "Reset your astro, astro upgrades, and previous contents for measure.": "重置您的 天文、天文升级和以前的测量内容。",
    "Reset your measure, measure upgrades, and previous contents for Planets.": "为 行星 重置您的测量、测量升级和以前的内容。",
    "Reset your planetarium, planetarium upgrades, and level for astro.": "重置您的天文馆、天文馆升级和 天文 等级。",
    "Ring Tree": "环树",
    "Rings": "环",
    "Rings gain is increased by": "环增益增加",
    "SP gain is raised to the": "SP增益提高到",
    "SP gained every grass-jump.": "SP 获得了每一次跳草。",
    "Start Vaporizing": "开始汽化",
    "Stellar Obelisk": "恒星方尖碑",
    "The Observatory": "天文台",
    "To earn rings, reset planetarium, level, astrolabe, and quadrant. Check upgrades in star chart.": "要获得环，请重置天文馆、等级、星盘和象限。 检查星图中的升级。",
    "To reach the planetary tier, you must reach Level": "要达到行星等级，您必须达到等级",
    "Unlock": "开锁",
    "Unnatural Realm": "非自然领域",
    "Use the Astrolabe": "使用星盘",
    "Use the Quadrant": "使用象限",
    "Vaporizer": "汽化器",
    "Vaporizer passively generates cloud based on NP & tier. Click \"Start Vaporizing\" to generate.": "汽化器根据 NP 和层被动生成云。 点击“Start Vaporizing”生成。",
    "You have grass-jumped": "你跳草了",
    "You have reached Planetary Tier": "您已达到行星等级",
    "You may enter or exit the Planetoid. During the Planetoid, pre-planetoid resources' production is paused, wiped by Galactic.": "您可以进入或退出小行星。 在小行星期间，前小行星资源的生产被暂停，被银河抹去。",
    "Active:": "活动：",
    "After level 200 of any lunar obelisk that includes only exponential boost, its effect will be softcapped!": "任何仅包含指数提升的月球方尖碑达到 200 级后，其效果将被软顶！",
    "Lunar Power:": "月球能量：",
    "Endgame: Level 27,000+; Astral Prestige 2; Grass Jump 12+; Planetary Tier 10+;": "残局：等级 27,000+； 星界声望 2； 草地跳跃 12+； 行星等级 10+；",
    "\n    Reset everything the planetary does as well as planets and planetary upgrades.": "\n 重置行星所做的一切以及行星和行星升级。",
    ". It's not affected by Echo.": "。 它不受 Echo 影响。",
    "(if multiplier goes above 1)": "（如果乘数超过 1）",
    "(in constellation).": "（在星座中）。",
    "(on top of star chart).": "（在星图顶部）。",
    "Additively boost the power of reinforcements by": "通过以下方式额外增强强化物的力量",
    "after compaction.": "压实后。",
    "Arcs, if must be placed adjacent to 2+ Moons with tier of 4+. Higher moon tier means higher generation!": "弧线，如果必须放置在 2 个以上 4+ 等级的卫星附近。 更高的月球等级意味着更高的世代！",
    "Bonuses": "奖金",
    "Boost the power of adjacent constellations and their instability by": "通过以下方式增强邻近星座的力量及其不稳定性",
    "Boost the power of Generators, Moons, Rings and Bolts by": "通过以下方式增强发电机、卫星、环和螺栓的功率",
    "Buildings": "建筑物",
    "Charge Milestone Multiplier:": "收费里程碑乘数：",
    "Constellation": "星座",
    "Constellation Upgrades": "星座升级",
    "Cost:": "成本：",
    "Dark Charge rate every grass-jump, starting at 20.": "每次草跳的黑暗冲锋率，从 20 开始。",
    "Dark Charger": "黑暗充电器",
    "OFF": "关闭",
    "Divide the instability generation of adjacent constellations by": "将相邻星座的不稳定性产生除以",
    "Endgame: Level 100,000+; Astral Prestige 5; Grass Jump 30+; Planetary Tier 37+; (projected)": "残局：等级100,000+； 星界威望 5； 草跳30+； 行星等级 37+； （预计）",
    "every zero grasshop grass-skips, ending at 60.": "每零个grasshop跳草，以60结束。",
    "First Constellation unlocks the building (on top-left of the reset).\n    ": "第一个星座解锁建筑物（位于重置的左上角）。\n",
    "Form a Constellation": "组成星座",
    "Grass Gain": "草增益",
    "Grow speed is increased": "生长速度增加",
    "Increase lunar powers gain by": "增加月球力量增益",
    "Increase rings gain by": "环增益增加",
    "Increase Stellaris limit by": "将 Stellaris 限制增加",
    "Increase the instability by": "增加不稳定性",
    "Increase the instability limit by": "增加不稳定极限",
    "Increase the power of the constellation to the left tile by": "将左侧图块的星座能量增加",
    "Instability: 0 / 0": "不稳定：0 / 0",
    "Instability: 0.0 / 5.0": "不稳定度：0.0/5.0",
    "Keep grasshop & grass-skip on galactic/sacrifice.": "让grasshop和grass-skip保持在银河/牺牲上。",
    "Lines.": "直线。",
    "Load": "加载",
    "Lunar Obelisk": "月球方尖碑",
    "Milestone Multiplier:": "里程碑乘数：",
    "more lunar slot per 5 planetary tiers, starting at 10.": "从第 10 层开始，每 5 个行星层有更多的月球位置。",
    "No Boosts": "无提升",
    "Normal Realm Multiplier:": "普通领域乘数：",
    "Other Multiplier:": "其他乘数：",
    "Presets": "预设",
    "Really Grass Cutting Incremental - v0.4.5 - Constellation Experimental Test - Made by MrRedShark77": "真正的割草增量 - v0.4.5 - 星座实验测试 - 由 MrRedShark77 制作",
    "Reduce the instability of adjacent constellations by": "减少相邻星座的不稳定性",
    "Sell All": "全部出售",
    "The J": "J",
    "Total Exponent:": "总指数：",
    "Total grass gain:": "总草增益：",
    "Uses up": "用完",
    "Will stop getting zero grasshop and more grass-skips.": "将不再获得零草铺和更多草草。",
    "You can equip": "你可以装备",
    "Experience Gain": "经验增益",
    "Total XP gain:": "总计经验增益：",
    "Anonymity Points Gain": "匿名点数增益",
    "Anti-Realm Multiplier:": "反领域乘数：",
    "Base before multiplier:": "乘数前的基数：",
    "Base Multiplier:": "基础乘数：",
    "Charge Rate": "收费率",
    "Crystal Gain": "水晶增益",
    "Foundry Effect:": "代工效果：",
    "Platinum Gain": "白金收益",
    "Prestige Points Gain": "声望点数增益",
    "Steel Gain": "钢增益",
    "Tier Multiplier:": "等级乘数：",
    "Tier Points Gain": "等级积分增益",
    "Total AP gain:": "总 AP 增益：",
    "Total charge rate:": "总收费率：",
    "Total Crystal gain:": "总水晶增益：",
    "Total Platinum gain:": "白金总收益：",
    "Total PP gain:": "总 PP 增益：",
    "Total Steel gain:": "钢材总收益：",
    "Total TP gain:": "总TP收益：",
    "\n            - Keep Automation, Anti-Anti-Automation, and Star Chart Automation upgrades on Supernova and Galactic.": "\n - 在超新星和银河上保持自动化、反反自动化和星图自动化升级。",
    "\n            - Unlock a new grass jump milestone.": "\n - 解锁新的跳草里程碑。",
    "\n            - Unlock Eclipse, and earn Solar Rays (SR) from Supernova.": "\n - 解锁日食，并从超新星获得太阳光芒 (SR)。",
    "\n    Reset EVERYTHING up to this point!": "\n 重置一切到此为止！",
    "\n    Warp Length:": "\n 扭曲长度：",
    "- Automatically buy ring upgrades.": "- 自动购买环升级。",
    "- Keep best Anonymity/Liquefy/Normality/Vaporize on Supernova.": "- 在超新星上保持最佳的匿名/液化/正常/蒸发。",
    "- Keep Reservatorium Ring Generation upgrades on Supernova.": "- 在超新星上保持储存环世代升级。",
    "- Keep rocket fuel and moonstone upgrades on Supernova.": "- 在超新星上保留火箭燃料和月光石升级。",
    "- Keep Steel Generation upgrades on Supernova.": "- 在 Supernova 上保持钢铁世代升级。",
    "- Planetarium is increased": "- 天文馆增加",
    "- Stars and Rings are increased": "- 星星和环增加",
    "- Tier": "- 等级",
    "(next tier at": "（下一层位于",
    "Advanced Upgrades": "高级升级",
    "Artist(-s): Bézier": "艺术家：贝塞尔",
    "Automation": "自动化",
    "Basic Upgrades": "基本升级",
    "Become Supernova": "成为超新星",
    "Challenge": "挑战",
    "Crazy Machine": "疯狂机器",
    "Crystallize once to Unlock": "结晶一次即可解锁",
    "DO IT NOW!": "现在做！",
    "Doing this will allow you to use upgrades, generate currencies, and auto grasshop/skip/jump from all three realms at the same time.": "这样做将允许您同时使用升级、生成货币以及从所有三个领域进行自动草铺/跳过/跳跃。",
    "Endgame (Spoiler)": "终局之战（剧透）",
    "Filler Upgrades": "填料升级",
    "Gain more Solar Shards based on your current star tier and star growth.\n    ": "根据您当前的星级和星级成长情况获得更多太阳能碎片。\n",
    "Gain more Stardusts based on planetary tier, starting at 40.": "根据行星等级获得更多星尘，从 40 级开始。",
    "Grass Field": "草地",
    "Ground": "地面",
    "Grow Speed:": "生长速度：",
    "Hop-Skip-Jump": "跳跳",
    "in the planetoid (on right of constellation).": "在小行星上（星座右侧）。",
    "Increase solar rays gain by": "增加太阳光线增益",
    "Level 300,000+; Planetary Tier 85+; Supernova Tier 3-4;": "等级300,000+； 行星等级 85+； 超新星 3-4 级；",
    "Map": "地图",
    "Next warp in:": "下一个扭曲在：",
    "Offline Progress:": "离线进度：",
    "Offline Progress!": "离线进度！",
    "on bottom of Grass Jump.": "在草跳的底部。",
    "Options": "选项",
    "Perks": "福利",
    "Prestige Field": "声望领域",
    "Really Grass Cutting Incremental - v0.5 - Supernova Update Part 1 - Made by MrRedShark77": "真正的割草增量 - v0.5 - 超新星更新第 1 部分 - 由 MrRedShark77 制作",
    "Remnant Upgrades": "剩余升级",
    "Skip Offline Progress": "跳过离线进度",
    "SN 2": "序列号2",
    "Solar Flare Upgrades": "太阳耀斑升级",
    "Space": "太空",
    "Special Factory": "特殊工厂",
    "Star": "星星",
    "Star -": "星星 -",
    "Stardust Upgrades": "星尘升级",
    "Supernova": "超新星",
    "Supernova Tier": "超新星层",
    "the Star": "星",
    "The Star": "星",
    "The Warp will give you offline progress equals to its length at the cost of one wrap.": "扭曲将为您提供相当于其长度的离线进度，但需要绕一圈。",
    "Ticks": "Tick",
    "Time Warp": "时间扭曲",
    "Time Warp!": "时间扭曲！",
    "Warps Left:": "向左扭曲：",
    "wtf!!!": "卧槽！！！",
    "You were gone offline for": "您离线的时间为",
    "Your Star Growth is": "您的明星成长是",
    "Astro Grow Speed": "天文成长速度",
    "Astro Rings": "天文环",
    "Increase grow speed by": "增加生长速度",
    "Increase observatorium gain by": "增加天文台增益",
    "Increase planetarium gain by": "增加天文馆增益",
    "Increase ring gain by": "将环增益增加",
    "Measured Observatorium II": "实测天文台 II",
    "Measured Planetarium": "测量的天文馆",
    "Measured Ring": "测量环",
    "Measures": "测量",
    "Reservatorium.": "储存。",
    "Ring Form": "环型",
    "Rings,": "环，",
    "This effect is increased by": "该效果增加",
    "Advanced Amplifier  [T2]": "高级增幅器[T2]",
    "Advanced Arc  [T2]": "高级电弧[T2]",
    "Advanced Bolt  [T2]": "高级螺栓 [T2]",
    "Advanced Bulwark  [T2]": "高级壁垒 [T2]",
    "Advanced Diminisher  [T2]": "高级减法器 [T2]",
    "Advanced Echo  [T2]": "高级回声 [T2]",
    "Advanced Generator  [T2]": "高级发电机 [T2]",
    "Advanced Magnifier  [T2]": "高级放大镜[T2]",
    "Advanced Moon  [T2]": "高级月亮 [T2]",
    "Advanced Reinforcement  [T2]": "高级强化[T2]",
    "Advanced Ring  [T2]": "高级环[T2]",
    "Advanced Stabilizer  [T2]": "高级稳定器[T2]",
    "Advanced Stellarium  [T2]": "高级星辰[T2]",
    "Allow grass-skipping multiple times. (change in options)": "允许多次跳草。 （选项的改变）",
    "Allow grasshopping multiple times. (change in options)": "允许多次跳草。 （选项的改变）",
    "Arc Constellation": "弧形星座",
    "Assembler Autobuy": "汇编器自动购买",
    "Auto-Grass-skip": "自动跳草",
    "Auto-Grasshop": "自动草铺",
    "Autocut Value Moonstone": "自动切割价值月光石",
    "Automate Assembler upgrades.": "自动汇编程序升级。",
    "Automate Foundry upgrades.": "自动化 Foundry 升级。",
    "Automate Generator upgrades.": "自动生成器升级。",
    "Automate Grass-skip. (change in grass-skip)": "自动跳草。 （跳草的变化）",
    "Automate Grasshop. (change in grasshop)": "自动化 Grashop。 （草铺的变化）",
    "Automate Momentum upgrades, they no longer spend Momentum.": "自动进行 Momentum 升级，他们不再花费 Momentum。",
    "Automate Platinum upgrades.": "自动白金升级。",
    "Automate Rocket Fuel, it will no longer spend resources.": "自动化火箭燃料，将不再花费资源。",
    "Automate Rocket Part, and it no longer resets anything except rocket fuel.": "自动化火箭部件，除了火箭燃料之外，它不再重置任何东西。",
    "Basic Bolt  [T1]": "基本螺栓 [T1]",
    "Boost dark charge rate by": "提高暗充电率",
    "Boosts: Dark Charge": "增强：暗充能",
    "Boosts: Rings": "强化：环",
    "Compaction Bonus:": "压实奖励：",
    "Dark Charge.": "暗电荷。",
    "Delete Mode: ON": "删除模式：开",
    "Exa Amplifier  [T8]": "Exa放大器 [T8]",
    "Exa Arc  [T8]": "Exa弧线 [T8]",
    "Exa Bolt  [T8]": "Exa螺栓 [T8]",
    "Exa Generator  [T8]": "Exa 发电机 [T8]",
    "Exa Moon  [T8]": "Exa月亮 [T8]",
    "Exa Reinforcement  [T8]": "Exa强化[T8]",
    "Exa Ring  [T8]": "Exa环 [T8]",
    "Exa Stabilizer  [T8]": "Exa 稳定器 [T8]",
    "Foundry Autobuy": "代工厂自动购买",
    "Generator Autobuy": "发电机自动购买",
    "Giga Amplifier  [T5]": "千兆放大器[T5]",
    "Giga Arc  [T5]": "千兆电弧 [T5]",
    "Giga Bolt  [T5]": "千兆螺栓 [T5]",
    "Giga Generator  [T5]": "千兆发电机[T5]",
    "Giga Moon  [T5]": "千兆月 [T5]",
    "Giga Reinforcement  [T5]": "千兆强化[T5]",
    "Giga Ring  [T5]": "千兆环[T5]",
    "Giga Stabilizer  [T5]": "千兆稳定器[T5]",
    "Increase arc gain compounding by": "增加电弧增益复合",
    "Increase line gain compounding by": "增加直线增益复利",
    "Increase XP gain compounding by": "增加 XP 增益复合",
    "Increases grass gain by": "增加草量",
    "Increases oil gain by": "增加石油增益",
    "Increases TP by": "TP 增加",
    "Increases XP gain by": "增加 XP 增益",
    "Instability: 101,331,000 / 144,179,205": "不稳定：101,331,000 / 144,179,205",
    "Line Constellation": "直线星座",
    "Mega Amplifier  [T4]": "巨型增幅器 [T4]",
    "Mega Arc  [T4]": "巨型弧线 [T4]",
    "Mega Bolt  [T4]": "巨型闪电 [T4]",
    "Mega Generator  [T4]": "巨型发电机 [T4]",
    "Mega Moon  [T4]": "超级月亮 [T4]",
    "Mega Reinforcement  [T4]": "超级强化[T4]",
    "Mega Ring  [T4]": "巨型环 [T4]",
    "Mega Stabilizer  [T4]": "巨型稳定器 [T4]",
    "Mega Stellarium  [T4]": "巨型星辰 [T4]",
    "Momentum Autobuy": "动量自动购买",
    "moonstone": "月光石",
    "Multi Grass-Skip": "批量草跳",
    "Peta Amplifier  [T7]": "佩塔增幅器 [T7]",
    "Peta Arc  [T7]": "佩塔弧线 [T7]",
    "Peta Bolt  [T7]": "佩塔螺栓 [T7]",
    "Peta Generator  [T7]": "必达发生器 [T7]",
    "Peta Moon  [T7]": "佩塔月亮 [T7]",
    "Peta Reinforcement  [T7]": "佩塔强化 [T7]",
    "Peta Ring  [T7]": "佩达环 [T7]",
    "Peta Stabilizer  [T7]": "佩塔稳定器 [T7]",
    "Planetarium Arc": "天文馆弧",
    "Planetarium Constellation": "天文馆星座",
    "Platinum Upgrade Autobuy": "白金升级自动购买",
    "Powerful Amplifier  [T3]": "强力增幅器[T3]",
    "Powerful Arc  [T3]": "强力电弧[T3]",
    "Powerful Bolt  [T3]": "强力螺栓 [T3]",
    "Powerful Bulwark  [T3]": "强大的壁垒 [T3]",
    "Powerful Diminisher  [T3]": "强力消减器 [T3]",
    "Powerful Generator  [T3]": "强力发电机[T3]",
    "Powerful Magnifier  [T3]": "强力放大镜[T3]",
    "Powerful Moon  [T3]": "强月[T3]",
    "Powerful Reinforcement  [T3]": "强力强化[T3]",
    "Powerful Ring  [T3]": "强力环[T3]",
    "Powerful Stabilizer  [T3]": "强力稳定器[T3]",
    "Powerful Stellarium  [T3]": "强大的星辰[T3]",
    "Rocket Fuel Automation": "火箭燃料自动化",
    "Rocket Part Autobuy": "火箭零件自动购买",
    "Selected!": "已选中！",
    "Space Multiplier:": "空间乘数：",
    "Star Chart": "星图",
    "Stellar Charger III": "恒星充电器III",
    "Stellar Charger IV": "恒星充电器 IV",
    "Stellar Grass II": "星辰草II",
    "Stellar Oil II": "恒星油II",
    "Stellar Oil III": "恒星油 III",
    "Stellar TP II": "恒星TP II",
    "Stellar XP II": "恒星 XP II",
    "Stellaris: 0 / 0": "群星: 0 / 0",
    "Stellaris: 14 / 18": "群星：14 / 18",
    "Tera Amplifier  [T6]": "兆级增幅器 [T6]",
    "Tera Arc  [T6]": "太拉弧 [T6]",
    "Tera Bolt  [T6]": "太拉闪电 [T6]",
    "Tera Generator  [T6]": "太拉发电机 [T6]",
    "Tera Moon  [T6]": "太拉月 [T6]",
    "Tera Reinforcement  [T6]": "太拉强化[T6]",
    "Tera Ring  [T6]": "太拉环 [T6]",
    "Tera Stabilizer  [T6]": "泰拉稳定器 [T6]",
    "to Charge Rate.": "收费率。",
    "to Cosmic Gain.": "到宇宙增益。",
    "to Lines Gain.": "至直线增益。",
    "to Lunar Powers Gain.": "到月球力量增益。",
    "to SP Gain.": "至 SP 增益。",
    "Unnatural Realm Multiplier:": "非自然领域乘数：",
    "XP Arc": "XP 弧线",
    "XP Constellation": "XP星座",
    "Yotta Amplifier  [T10]": "尤塔增幅器 [T10]",
    "Yotta Generator  [T10]": "尤塔发电机 [T10]",
    "Yotta Moon  [T10]": "尤塔·穆恩 [T10]",
    "Yotta Reinforcement  [T10]": "约塔强化[T10]",
    "Yotta Ring  [T10]": "尤塔环 [T10]",
    "Yotta Stabilizer  [T10]": "尤塔稳定器[T10]",
    "You can now automatically buy the Factory upgrades.": "您现在可以自动购买工厂升级。",
    "You have 9.41e129": "你有 9.41e129",
    "Zetta Amplifier  [T9]": "泽塔增幅器[T9]",
    "Zetta Bolt  [T9]": "泽塔闪电 [T9]",
    "Zetta Generator  [T9]": "泽塔发生器 [T9]",
    "Zetta Moon  [T9]": "泽塔月亮 [T9]",
    "Zetta Reinforcement  [T9]": "泽塔强化[T9]",
    "Zetta Ring  [T9]": "泽塔环 [T9]",
    "Zetta Stabilizer  [T9]": "泽塔稳定器[T9]",
    ", and they no longer spend.": "，他们不再花钱。",
    "' maximum level (except": "' 最大级别（除了",
    "' maximum level, except Planetarium Grow Speed & Planetarium Range.\n        ": "' 最高等级，天文馆生长速度和天文馆范围除外。\n",
    "' maximum level.": "' 最高级别。",
    "' maximum level.\n        ": "' 最大级别。\n",
    "' maximum limit by": "' 最大限制为",
    "'s maximum level.": "的最高等级。",
    "5.54e98 Rings": "5.54e98 环",
    "A Normal Upgrade": "正常升级",
    "Advanced Cosmic": "高级宇宙",
    "Advanced Lunar Power": "先进的月球能量",
    "Advanced Observatorium": "高级天文台",
    "Advanced Planetarium": "高级天文馆",
    "Advanced Reservatorium": "高级储存",
    "Advanced SP": "高级SP",
    "Advanced Star": "进阶之星",
    "and": "和",
    "Anti-Tier Boost": "反层提升",
    "are not reset on sacrifice.": "不会因牺牲而重置。",
    "Astral to Cosmic": "星体到宇宙",
    "Astro Automation": "天文自动化",
    "Astro Generation": "天文世代",
    "Autocut grass/planetarium is always": "自动切草/天文馆总是",
    "Automate": "自动化",
    "Basic Cosmic": "基本宇宙",
    "Basic Grass Cap": "基本草帽",
    "Basic Lunar Power": "基本月球能量",
    "Basic Observatorium": "基本天文台",
    "Basic Planetarium": "基础天文馆",
    "Basic Reservatorium": "基础储存",
    "Basic SP": "基本SP",
    "Basic TP": "基本TP",
    "Basic XP": "基础XP",
    "Beyond Fun": "超越乐趣",
    "boost to Grass, XP & TP.": "提升草、XP 和 TP。",
    "Charge's SFRGT milestone now works outside anti-realm.": "Charge 的 SFRGT 里程碑现在可以在反领域之外使用。",
    "Cloud Automation": "云自动化",
    "Compaction now affects planetarium, cosmic, and observatorium.": "压缩现在影响天文馆、宇宙和天文台。",
    "compounding per level.": "每级复利。",
    "Cosmic Exponent": "宇宙指数",
    "Dark Charge I": "暗电荷 I",
    "Dark Matter Automation": "暗物质自动化",
    "Dark Matter Generation": "暗物质的产生",
    "Decrease level threshold by": "将级别阈值降低",
    "Decrease tier threshold by": "将层级阈值降低",
    "Final Dark Charge": "最后的暗电荷",
    "Final Line": "最终线",
    "Final Observatorium": "最后的天文台",
    "Final Reinforcement": "最后的加固",
    "Final Stabilizer": "最终稳定器",
    "Foundry Upgrades": "铸造厂升级",
    "Fun & SFRGT Upgrades": "乐趣和 SFRGT 升级",
    "Fun Generation": "有趣的世代",
    "Funny Automation": "有趣的自动化",
    "Funspansion": "芬斯潘森",
    "Giga Cosmic": "千兆宇宙",
    "Giga Observatorium": "千兆天文台",
    "Giga Planetarium": "巨型天文馆",
    "in": "在",
    "Increase": "增加",
    "Increase astro gain by": "增加天文增益",
    "Increase cosmic exponent by": "宇宙指数增加",
    "Increase cosmic gain by": "增加宇宙增益",
    "Increase dark charge rate by": "增加暗充电率",
    "Increase dark charge rate compounding by": "增加暗电荷复合率",
    "Increase first scaled level starting by": "增加第一个缩放级别，起始位置为",
    "Increase lines gain by": "增加直线增益",
    "Increase lunar power gain by": "增加月球能量增益",
    "Increase measure gain by": "将测量增益增加",
    "Increase observatorium gain compounding by": "增加天文台增益复利",
    "Increase planetarium exponent by": "将天文馆指数增加",
    "Increase reinforcement by": "增加强化",
    "Increase reinforcement power compounding by": "增加强化力量复合",
    "Increase ring generation by": "增加环生成量",
    "Increase rocket fuel's cheapness by": "提高火箭燃料的便宜度",
    "Increase second scaled level starting by": "增加第二个缩放级别，起始位置为",
    "Increase SP gain by": "SP增益增加",
    "Increase SP's exponent by": "将 SP 的指数增加",
    "Increase stabilizer power by": "增加稳定器功率",
    "Increase stabilizer power compounding by": "增加稳定器功率复合",
    "Increase star gain by": "增加星星获得量",
    "Intermediate Cosmic": "中级宇宙",
    "Intermediate Observatorium": "中级展望台",
    "Intermediate Planetarium": "中级天文馆",
    "Intermediate Reservatorium": "中级储存",
    "Intermediate SP": "中级SP",
    "Intermediate Star": "中级明星",
    "Level Threshold": "级别阈值",
    "Limit Generator": "极限发生器",
    "Limitless Foundry": "无限铸造厂",
    "Limitless Normality Upgrades": "无限常态升级",
    "Limitless Planetarium Upgrades": "无限天文馆升级",
    "Limitless Unnatural Upgrades": "无限的非自然升级",
    "Line I": "直线 I",
    "Measure Automation": "测量自动化",
    "Measure Generation": "测量生成",
    "Mega Cosmic": "超级宇宙",
    "Mega Observatorium": "巨型天文台",
    "Mega Planetarium": "巨型天文馆",
    "Momentum Generation": "动力生成",
    "More Rocket Fuels": "更多火箭燃料",
    "More Rocket Fuels II": "更多火箭燃料 II",
    "no longer spend ring.": "不再花环。",
    "Normality Automation": "常态自动化",
    "of astro you would earn on astrolabe per second.": "您每秒可以通过星盘赚到 astro 的钱。",
    "of dark matter you would earn on sacrifice per second.": "你每秒可以通过牺牲获得暗物质的数量。",
    "of fun you would earn on funify per second.": "您每秒可以在 funify 上获得的乐趣。",
    "of measure you would earn on quadrant per second.": "您每秒将在象限上赚取的衡量标准。",
    "of momentum you would earn on rocket part per second.": "您每秒将获得火箭部分的动量。",
    "of planet you would earn on planetary per second.": "您每秒将在行星上赚取的行星数。",
    "of ring you would earn on forming ring per second.": "每秒形成环您将赚取的环。",
    "of stars you would earn on galactic per second.": "您每秒可以在银河上获得的星星数。",
    "of your observatorium will be converted to reservatorium on forming the ring.": "形成环后，您的天文台将转变为自然保护区。",
    "On first purchase, increase observatorium chance to": "首次购买时，增加天文台机会",
    "Passively generate NP based off of your best normality, starts at 1% of best. Also, keep best liquefy/anonymity on galactic.": "根据您的最佳常态被动生成 NP，从最佳常态的 1% 开始。 另外，在银河上保持最好的液化/匿名性。",
    "Passively generates": "被动生成",
    "Planet Automation": "星球自动化",
    "Planet Generation": "行星世代",
    "Planetarium Automation": "天文馆自动化",
    "Planetarium Exponent": "天文馆指数",
    "Planetoid Compaction": "小行星压实",
    "Powerful Cosmic": "强大的宇宙",
    "Powerful Observatorium": "强大的天文台",
    "Powerful Planetarium": "强大的天文馆",
    "Prestige & Crystal Charges": "声望和水晶费用",
    "Reinforcement I": "强化 I",
    "Reinforcement II": "强化 II",
    "Reserved Rings": "预留环",
    "Return to Autocut": "返回自动剪切",
    "Ring Generation": "环代",
    "Ring Generation II": "环第二代",
    "Ring Generation III": "第三代环",
    "Ring Generation IV": "第四代环",
    "Ring Upgrades": "环升级",
    "Ring-Free Star Chart": "无环星图",
    "Ringy SP Exponent": "环形 SP 指数",
    "SFRGT Generation": "SFRGT世代",
    "SFRGT Upgrades": "SFRGT 升级",
    "Space Power II": "太空力量II",
    "Space Power III": "太空力量III",
    "Space Power IV": "太空力量IV",
    "Stabilizer I": "稳定剂 I",
    "Stabilizer II": "稳定器 II",
    "Star Generation": "明星世代",
    "Stellar Scaled Level": "恒星等级",
    "Stellar Scaled Level II": "恒星级 II 级",
    "Tier multiplier (base of 2) in anti-realm gives a": "反领域中的等级乘数（以 2 为底）给出",
    "Tier Threshold": "等级门槛",
    "Tier to SP Boost": "SP提升等级",
    "to base that boosts Cosmic by Astral per level. (starting base is 1).": "到每级星体提升宇宙的基础。 （起始基数为 1）。",
    "to base that boosts SP by Tier per level. (starting base is 1)": "到每级提升 SP 的基地。 （起始基数为1）",
    "Uncap": "非上限",
    "Unlocks new": "解锁新的",
    "Unnatural Automation": "不自然的自动化",
    "Unnatural Pre-Prestige Exponent": "不自然的预威望指数",
    "Unnatural Upgrades": "不自然的升级",
    "Welcome to the Planetarium": "欢迎来到天文馆",
    "Rocket fuel generation is permanently enabled and based on oil/charge generated per second, it requires oil drilling rig. The base of rocket fuel's requirement no longer increased by rocket parts, however, rocket part's requirement is changed.": "火箭燃料生成是永久启用的，并且基于每秒生成的石油/电荷，它需要石油钻机。 火箭燃料的需求基础不再因火箭部件而增加，但是火箭部件的需求发生了变化。",
    "Beyond Foundry": "超越铸造厂",
    "Constant RF": "恒定射频",
    "Double solar flare's capacity.": "双倍太阳耀斑容量。",
    "Generate best solar shards. This upgrade triggers everyday.": "生成最好的太阳能碎片。 此升级每天都会触发。",
    "Increase arcs generated by": "增加产生的弧",
    "Increase crystals gain by": "增加晶体增益",
    "Increase grass value by": "草价值增加",
    "Increase lines generated by": "增加生成的行数",
    "Increase lunar power rate by": "增加月球发电率",
    "Increase prestige points gain by": "增加声望点数增益",
    "Increase solar shards gain by": "增加太阳能碎片增益",
    "Increase star grow speed per supernova (based on level).": "提高每颗超新星的恒星生长速度（基于等级）。",
    "Increase stardust generated by": "增加星尘产生量",
    "Level 320,000+; Planetary Tier 85+; Supernova Tier 3-4;": "等级320,000+； 行星等级 85+； 超新星 3-4 级；",
    "of steel gained on reset per level.": "每级重置时获得的钢材数量。",
    "Orbit": "轨道",
    "per squared level.": "每平方等级。",
    "Planets boost planetarium.": "行星促进了天文馆的发展。",
    "Solar Flare Capacity": "太阳耀斑容量",
    "Solar Observatorium II": "太阳观测站 II",
    "Solar Powered Arcs II": "太阳能电弧 II",
    "Solar Powered Crystals": "太阳能晶体",
    "Solar Powered Lines II": "太阳能供电线 II",
    "Solar Powered Prestige": "太阳能威望",
    "Solar Shards": "太阳能碎片",
    "Solar Stardust II": "太阳能星尘 II",
    "Steel Generation": "钢铁世代",
    "Stellar Charger II": "恒星充电器II",
    "Stellar Grass III": "星辰草III",
    "Stellar Oil": "恒星油",
    "Stellar TP": "恒星TP",
    "Stellar TP III": "恒星TP III",
    "Stellar XP": "恒星XP",
    "Stellar XP III": "恒星 XP III",
    "Super Star": "超级明星",
    "Supercharged": "增压",
    "Supercharged Dark": "增压黑暗",
    "Superpower": "超级大国",
    "The Solar Idler": "太阳能惰轮",
    "Uncap the limit of Foundry effect, but softcap its effect at maxed effect.": "解除铸造厂效果的限制，但在最大效果时对其效果进行软限制。",
    "You can now passively generate": "您现在可以被动生成",
    "\n            - Passively generate sunstone (based on current stage) and remnants (based on total remnants from Eclipse) at": "\n - 被动生成日光石（基于当前阶段）和残余物（基于日食的总残余物）",
    "\n            - Unlock the": "\n - 解锁",
    "\n            - Unlock the third obelisk.": "\n - 解锁第三个方尖碑。",
    "- Dark Matter Upgrades' cap is broken.": "- 暗物质升级的上限被打破。",
    "- Eclipse no longer gets reset.": "- 日蚀 不再重置。",
    "- Solar Flares cap is increased by": "- 太阳耀斑上限增加",
    "- Unlock more remnant and sunstone upgrades.": "- 解锁更多遗迹和日光石升级。",
    "- Unlock the": "- 解锁",
    "??? Eclipse": "??? 蚀",
    "??? Mana": "??? 法力",
    "??? Star Growth": "??? 明星成长",
    "(based on collecting speed)": "（根据采集速度）",
    "(convert mana into darkness on sunset)": "（在日落时将法力转化为黑暗）",
    "A Bright Star (Star Growth)": "一颗明亮的星星（星星成长）",
    "Anonymity Points": "匿名点",
    "Anti-Grass": "反草",
    "Basic": "基本的",
    "Blocks of Creation (Forming)": "创造块（形成）",
    "Centralizing currency makes its multiplier equals to grass, except grass types (results that grass is squared).": "中心化货币使其乘数等于草，但草类型除外（结果是草是平方的）。",
    "Collection": "收藏",
    "Compression": "压缩",
    "Crystal": "水晶",
    "Darkness": "黑暗",
    "Divine Soul Upgrades": "神魂升级",
    "Divine Souls": "神圣灵魂",
    "Enemy": "敌人",
    "First Sunset": "第一个日落",
    "First Sunset unlocks Darkness in Forming tab and Divine Soul Upgrades Chart.": "第一落日在“成型”选项卡和“神魂升级表”中解锁“黑暗”。",
    "Forming": "成型",
    "Fragments": "碎片",
    "Fragments Collection": "碎片收藏",
    "Glimmer of Hope* (Divine Souls)": "希望之光*（神圣灵魂）",
    "Grass Essence": "草精",
    "Grass Exponent": "草指数",
    "in Forming tab.": "在“成型”选项卡中。",
    "Increase The Star": "增加星星",
    "Level 0 : ???": "0级：？？？",
    "Level 10,000,000+; Supernova Tier 9; Eclipse: 20,000+; Stage 110+; HSJ 3 (if may possible);": "等级10,000,000+； 超新星 9 级； 日食：20,000+； 阶段 110+； HSJ 3（如果可能）；",
    "Light Logs": "轻原木",
    "Light Logs Collection": "光原木采集",
    "Mana": "法力",
    "Materials/Collecting": "材料/采集",
    "Offense": "罪行",
    "Omega Star (Scaled Eclipse)": "欧米茄之星（鳞片日食）",
    "per Supernova Tier, starting at 4.": "通过 Supernova Tier，从 4 级开始。",
    "Portal Stones": "传送门石",
    "Portal Stones Collection": "传送门石采集",
    "Rank 0 : ???": "等阶 0：？？？",
    "rate.": "速度。",
    "Really Grass Cutting Incremental - v0.5.1.2 - Made by MrRedShark77": "真正的割草增量 - v0.5.1.2 - 由 MrRedShark77 制作",
    "reset (on bottom of supernova milestones).": "重置（在超新星里程碑的底部）。",
    "Reset eclipse, remnants, and remnant upgrades for sunstone.": "重置日食、遗迹和日光石遗迹升级。",
    "Reset everything does sunrise as well as Souls, Soul Upgrades, Sol Compaction, FM, and Darkness Upgrades (marked with *). Convert Mana into Darkness at full rate. Gain more divine souls based on soul, starting at 1 Qt.": "重置日出以及灵魂、灵魂升级、Sol Compaction、FM 和黑暗升级（标有 *）的一切。 全速将法力转化为黑暗。 基于灵魂获得更多神圣灵魂，从 1 Qt 开始。",
    "Restoration": "恢复",
    "Rise the Sun!!!": "太阳升起！！！",
    "Road to Success (Mana)": "成功之路（法力）",
    "Rocket Fuel": "火箭燃料",
    "Set the Sun down!!!": "把太阳放下来！！！",
    "Singularity Upgrades": "奇点升级",
    "Sol": "太阳",
    "Sol Collection": "太阳采集",
    "Sol Compression": "太阳压缩",
    "Soul Upgrades": "灵魂升级",
    "Soul'ed Offense": "灵魂进攻",
    "Souls": "灵魂",
    "Stage Bonuses": "阶段奖金",
    "Stats": "统计数据",
    "Sun Upgrades": "太阳升级",
    "Sunrise": "日出",
    "Sunrise FM": "日出调频",
    "Sunset": "日落",
    "T4 & Prism": "T4 & 棱镜",
    "Test": "测试",
    "The Best Defense (Offense)": "最佳防守（进攻）",
    "Trees of Recollection (Collecting)": "回忆之树（收藏）",
    "x??? to something": "X？？？ 对某事",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'O': 'O',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    ". Unlock perk autobuyer upgrade.": ". 解锁 天赋 自动购买器 升级。",
    "Keep perks on Prestige.": "重置时保留天赋。",
    "You can now automatically buy Grass Upgrades.": "您现在可以自动购买草升级。",
    "Increase Tier's effect base by ": "增加层级的效果基数 ",
    "Boost AP gain by ": "提升AP增益 ",
    "[progress-#": "[进度-#",
    "[auto-#": "[自动-#",
    "[speed-#": "[速度-#",
    "Basic Arc  ": "基础弧线",
    "Basic Bulwark  ": "基础壁垒 ",
    "Basic Diminisher  ": "基本减法器 ",
    "Basic Echo  ": "基础回声",
    "Basic Generator  ": "基础发电机 ",
    "Basic Magnifier  ": "基础放大镜 ",
    "Basic Moon  ": "基础月亮 ",
    "Basic Reinforcement  ": "基础强化",
    "Basic Ring  ": "基础环",
    "Basic Stabilizer  ": "基础稳定器",
    "Basic Stellarium  ": "基础星辰",
    "Basic Amplifier  ": "基础增幅器",
    "- Unlock constellation tiers ": "- 解锁星座层级 ",
    "compounding per grass jump, starting at ": "每跳草一次的复利，开始于 ",
    "Solar Shards: ": "太阳能碎片：",
    "Delete Mode: ": "删除模式：",
    "[reserv-#": "[储存-#",
    "[ring-#": "[环-#",
    "Solar Flares: ": "太阳耀斑：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "\n            ": "\n            ",
    " XP/cut": " 经验/割",
    " SP/cut": " SP/割",
    " TP/cut": " TP/割",
    " multiplier": " 经验乘数",
    " to Grass, XP, TP, PP & Crystal gain.": " 草、XP、TP、PP 和水晶增益。",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) NoQag$/,
    /^([\d\.]+) QtQag$/,
    /^([\d\.]+) Qag$/,
    /^([\d\.]+) DVg$/,
    /^([\d\.]+) SxNog$/,
    /^([\d\.]+) QtNog$/,
    /^([\d\.]+) QaQag$/,
    /^([\d\.]+) UQag$/,
    /^([\d\.]+) OcNog$/,
    /^([\d\.]+) QtOcg$/,
    /^([\d\.]+) SpDc$/,
    /^([\d\.]+) OcDc$/,
    /^([\d\.]+) Qt$/,
    /^([\d\.]+) TNog$/,
    /^([\d\.]+) DDc$/,
    /^([\d\.]+) TDc$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+) NoOcg$/,
    /^([\d\.]+) QtDc$/,
    /^([\d\.]+) UTg$/,
    /^([\d\.]+) SpVg$/,
    /^([\d\.]+) QtNog$/,
    /^([\d\.]+) SxNog$/,
    /^([\d\.]+) SpTg$/,
    /^([\d\.]+) NoDc$/,
    /^([\d\.]+) OcQag$/,
    /^([\d\.]+) SxQag$/,
    /^([\d\.]+) SxTg$/,
    /^([\d\.]+) SpSxg$/,
    /^([\d\.]+) OcTg PP$/,
    /^([\d\.]+) SpQag PP$/,
    /^([\d\.]+) SpTg PP$/,
    /^([\d\.]+) QtQag PP$/,
    /^([\d\.]+) QaQag PP$/,
    /^([\d\.]+) DQag PP$/,
    /^\+([\d\.]+) QtVg$/,
    /^\+([\d\.]+) QaNog$/,
    /^\+([\d\.]+) SxVg$/,
    /^\+([\d\.]+) SxNog$/,
    /^\+([\d\.]+) Qt$/,
    /^\+([\d\.]+) UDc$/,
    /^\+([\d\.]+) OcSpg$/,
    /^\+([\d\.]+) SpNog$/,
    /^\+([\d\.]+) SxSpg$/,
    /^\+([\d\.]+) Dc$/,
    /^\+([\d\.]+) T$/,
    /^\+([\d\.]+) QaDc$/,
    /^\+([\d\.]+) TDc$/,
    /^\+([\d\.]+) TDc$/,
    /^\+([\d\.]+) Vg$/,
    /^\+([\d\.]+) TQtg$/,
    /^\+([\d\.]+) SxSxg$/,
    /^\(([\d\.]+)\%\)$/,
    /^\(\+([\d\.]+)\/s\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) B PP$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^T([\d\.,]+)$/,
    /^([\d\.,]+) PP$/,
    /^([\d\.,]+) TP$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+) SP$/,
    /^([\d\.,]+) \/ ([\d\.,]+) XP$/,
    /^([\d\.,]+) \/ ([\d\.,]+) B XP$/,
    /^([\d\.,]+) B \/ ([\d\.,]+) B XP$/,
    /^([\d\.,]+) Dc \/ ([\d\.,]+) UDc$/,
    /^([\d\.,]+) No \/ ([\d\.,]+) UDc$/,
    /^([\d\.,]+) \/ ([\d\.,]+) TP$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^×([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) PP$/,
    /^\+([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) Moonstone$/, '你有 $1 个月光石'],
    [/^You have (.+) Moonstone \((.+) platinum grow chance\)$/, '你有 $1 个月光石（$2 铂金成长几率）'],
    [/^You have (.+) Measure$/, '你有 $1 测量'],
    [/^You have (.+) Astro$/, '你有 $1 天文'],
    [/^You have (.+) Line$/, '你有 $1 直线'],
    [/^You have (.+) Arc$/, '你有 $1 弧线'],
    [/^You have (.+) Grass$/, '你有 $1 草'],
    [/^You have (.+) Prestige Points$/, '你有 $1 声望点'],
    [/^You have (.+) Platinum$/, '你有 $1 白金'],
    [/^You have (.+) Platinum \((.+)\% grow chance\)$/, '你有 $1 白金 \($2\% 成长率\)'],
    [/^You have (.+) PP$/, '你有 $1 PP'],
    [/^Craft to (.+) Rocket Fuel$/, '制作 $1 火箭燃料'],
    [/^You have (.+) Crystal$/, '你有 $1 水晶'],
    [/^You have (.+) Observatorium \((.+) grow chance\)$/, '你有 $1 天文台（$2 成长几率）'],
    [/^\(\+(.+)\/sec\)$/, '（\+$1\/秒）'],
    [/^Boost XP gain by (.+)x$/, '将 经验值 增益提高 $1x'],
    [/^Boost steel gain by (.+)x$/, '将 钢 增益提高 $1x'],
    [/^Boost TP gain by (.+)x$/, '将 TP 增益提高 $1x'],
    [/^Boost PP gain by (.+)x$/, '将 PP 增益提高 $1x'],
    [/^Boost Crystal gain by (.+)x$/, '将 水晶 增益提高 $1x'],
    [/^Boost grass gain by (.+)x$/, '将 草 增益提高 $1x'],
    [/^You have (.+) Steel$/, '你有 $1 钢'],
    [/^You have (.+) Perk$/, '你有 $1 天赋'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Scaled level starts x(.+) later$/, '缩放级别在 x$1 之后开始'],
    [/^(.+) \/ (.+) TP$/, '$1 \/ $2 TP'],
    [/^(.+) \/ (.+) XP$/, '$1 \/ $2 经验值'],
    [/^(.+) \/ (.+) Cosmic$/, '$1 \/ $2 宇宙'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) Stars$/, '$1e$2 星星'],
    [/^\+([\d\.]+)e([\d\.,]+) Cosmic\/cut$/, '\+$1e$2 宇宙\/割草'],
    [/^\(\+([\d\.]+)\/sec\)$/, '（\+$1\/秒）'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) M Grass$/, '$1 M 草'],
    [/^([\d\.]+) B Grass$/, '$1 B 草'],
    [/^([\d\.]+) M Stars$/, '$1 M 星星'],
    [/^([\d\.]+) Sp Stars$/, '$1 Sp 星星'],
    [/^([\d\.]+) T Stars$/, '$1 T 星星'],
    [/^([\d\.]+) Qa Stars$/, '$1 Qa 星星'],
    [/^([\d\.]+) B Stars$/, '$1 B 星星'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Preset ([\d\.,]+)$/, '预设 $1'],
    [/^Supernova Tier ([\d\.,]+)$/, '行星层级 $1'],
    [/^Planetary Tier ([\d\.,]+)$/, '行星层级 $1'],
    [/^Supernova Tier ([\d\.,]+).$/, '超新星层级 $1。'],
    [/^Reach Level ([\d\.,]+).$/, '达到等级 $1。'],
    [/^\+([\d\.,]+) later$/, '\+$1 之后'],
    [/^Stage ([\d\.,]+)$/, '阶段 $1'],
    [/^([\d\.,]+) Perk$/, '$1 天赋'],
    [/^([\d\.,]+) Grass-skip$/, '$1 草跳'],
    [/^([\d\.,]+) Moonstone$/, '$1 月光石'],
    [/^([\d\.,]+) Platinum$/, '$1 白金'],
    [/^([\d\.,]+) M Platinum$/, '$1 M 白金'],
    [/^([\d\.,]+) Grass$/, '$1 草'],
    [/^([\d\.,]+) Grasshop$/, '$1 草场'],
    [/^([\d\.,]+) Stars$/, '$1 星星'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Stellaris$/, '$1 群星'],
    [/^([\d\.,]+) Lines$/, '$1 直线'],
    [/^([\d\.,]+) Grasshop and ([\d\.,]+) Grass\-skip$/, '$1 草场 和 $2 草跳'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost to next 25: (.+) PP$/, '到下一个 25 的成本：$1 PP'],
    [/^Cost to next 25: (.+) Measure$/, '到下一个 25 的成本：$1 测量'],
    [/^Cost to next 25: (.+) Astro$/, '到下一个 25 的成本：$1 天文'],
    [/^Cost to next 25: (.+) Stars$/, '到下一个 25 的成本：$1 星星'],
    [/^Cost to next 25: (.+) Solar Shard$/, '到下一个 25 的成本：$1 太阳碎片'],
    [/^Cost to next 25: (.+) Solar Flare$/, '到下一个 25 的成本：$1 太阳耀斑'],
    [/^Cost to next 25: (.+) Moonstone$/, '到下一个 25 的成本：$1 月光石'],
    [/^Cost to next 25: (.+) Steel$/, '到下一个 25 的成本：$1 钢'],
    [/^Cost to next 25: (.+) Line$/, '到下一个 25 的成本：$1 直线'],
    [/^Cost to next 25: (.+) Arc$/, '到下一个 25 的成本：$1 弧线'],
    [/^Cost to next 25: (.+) Rings$/, '到下一个 25 的成本：$1 环'],
    [/^Cost to next 25: (.+) Reservatorium$/, '到下一个 25 的成本：$1 储存'],
    [/^Cost to next 25: (.+) Crystal$/, '到下一个 25 的成本：$1 水晶'],
    [/^Cost to next 25: (.+) Platinum$/, '到下一个 25 的成本：$1 白金'],
    [/^Cost to next 25: (.+) Perk$/, '到下一个 25 的成本：$1 天赋'],
    [/^Cost to next 25: (.+) Grass$/, '到下一个 25 的成本：$1 草'],
    [/^Goal: Level (.+)$/, '目标：等级 $1'],
    [/^Goal: Tier (.+)$/, '目标：层级 $1'],
    [/^Cost: (.+) Solar Flare$/, '成本：$1 太阳耀斑'],
    [/^Cost: (.+) Solar Shard$/, '成本：$1 太阳碎片'],
    [/^Cost: (.+) Stars$/, '成本：$1 星星'],
    [/^Cost: (.+) Lines$/, '成本：$1 直线'],
    [/^Cost: (.+) Rings$/, '成本：$1 环'],
    [/^Cost: (.+) Reservatorium$/, '成本：$1 储存'],
    [/^Cost: (.+) Arcs$/, '成本：$1 弧线'],
    [/^Cost: (.+) Astro$/, '成本：$1 天文'],
    [/^Cost: (.+) Measure$/, '成本：$1 测量'],
    [/^Cost: (.+) Moonstone$/, '成本：$1 月光石'],
    [/^Cost: (.+) Steel$/, '成本：$1 钢'],
    [/^Cost: (.+) Crystal$/, '成本：$1 水晶'],
    [/^Cost: (.+) Grass$/, '成本：$1 草'],
    [/^Cost: (.+) Arc$/, '成本：$1 弧线'],
    [/^Cost: (.+) Line$/, '成本：$1 直线'],
    [/^Cost: (.+) Perk$/, '成本：$1 天赋'],
    [/^Cost: (.+) PP$/, '成本：$1 PP'],
    [/^Cost: (.+) Platinum$/, '成本：$1 白金'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(.+) Lines, (.+) Arcs$/, '$1 直线，$2 弧线'],
    [/^(.+) Arcs$/, '$1 弧线'],
    [/^(.+) Lines$/, '$1 直线'],
    [/^(.+) Reservatorium$/, '$1 储存'],
    [/^(.+) Grass$/, '$1 草'],
    [/^(.+) Crystal$/, '$1 水晶'],
    [/^Steel Steel$/, '钢 钢'],
    [/^(.+) Steel$/, '$1 钢'],
    [/^(.+) → (.+)$/, '$1 → $2'],

]);