/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "/cut": "/割草",
    "Auto: OFF": "自动：关闭",
    "Automation Upgrades": "自动化升级",
    "Buy 1": "购买 1",
    "Buy All": "购买全部",
    "Buy Max": "购买最大",
    "Cancel": "取消",
    "Click any challenge to start! Click again to exit.": "点击任何挑战开始！再次单击退出。",
    "Crystal Upgrades": "水晶升级",
    "Crystallize": "结晶",
    "Crystallizing resets everything prestige as well except Platinum for Crystals.": "结晶也会重置所有声望，除了水晶的铂金。",
    "Effect:": "影响：",
    "Endgame: Level 370, Tier 24, 7 Grasshop": "残局：370 级、24 级、7 级草场",
    "every completions.": "每个完成。",
    "every grasshop.": "每一个草场。",
    "every grasshop. Keep Prestige challenges on Grasshop.": "每一个草场。在 Grasshop 上保持声望挑战。",
    "every grasshop. Unlock more automation upgrades.": "每一个草场。解锁更多自动化升级。",
    "Gain": "获得",
    "Gain more Crystals based on your tier and PP.": "根据您的等级和 PP 获得更多水晶。",
    "Gain more PP based on your level and grass.": "根据你的等级和草获得更多的 PP。",
    "Goal: ???": "目标： ？？？",
    "Grass Cutting Incremental": "割草增量",
    "Grass Upgrades": "草升级",
    "Grasshop": "蚱蜢",
    "Grasshop once to unlock.": "Grasshop 一次解锁。",
    "Grasshop!": "草蜢！",
    "Grasshopping resets everything crystalize does as well as crystals, crystal upgrades, challenges.": "蚱蜢重置一切结晶以及水晶，水晶升级，挑战。",
    "Grassless": "无草",
    "Hard Reset": "硬重置",
    "Hide upgrades which is maxed/purchased:": "隐藏已最大化/购买的升级：",
    "Inactive": "不活跃",
    "Join Discord Server": "加入 Discord 服务器",
    "Keep Crystallize challenges on Grasshop.\n            ": "在 Grasshop 上保持 Crystallize 挑战。\n",
    "Less Level": "更少的等级",
    "Level": "等级",
    "more grass. Grass gain is increased by": "更多的草。草增益增加",
    "more TP. TP gain is increased by": "更多的TP。 TP 增益增加",
    "more XP. XP gain is increased by": "更多经验值。 XP增益增加",
    "No Tiers": "无等级",
    "per completion.": "每次完成。",
    "per grasshop (start at 3). Unlock more automation upgrades.": "每个草场（从 3 开始）。解锁更多自动化升级。",
    "Perk Upgrades": "天赋升级",
    "Platinum Chance": "白金几率",
    "Platinum Upgrades": "白金升级",
    "Platinum worth": "白金价值",
    "Prestige": "声望",
    "Prestige Upgrades": "声望升级",
    "Prestigeless": "没有声望",
    "Prestiging resets your grass, grass upgrades, level and perks for Prestige Points (PP).": "声望会重置你的草、草升级、等级和天赋对于声望点 (PP)。",
    "Reach Level 200 to unlock": "达到200级解锁",
    "Really Grass Cutting Incremental - Prototype v0.3 - Made by MrRedShark77": "真正的割草增量 - Prototype v0.3 - 由 MrRedShark77 制作",
    "Reduced Resources": "减少资源",
    "Reward: Grass gain is increased by": "奖励：草增益增加",
    "Reward: Grass multiplier's exponent is increased by": "奖励：草乘数的指数增加",
    "Reward: PP gain is increased by": "奖励：PP增益增加",
    "Reward: TP gain is increased by": "奖励：TP增益增加",
    "Reward: XP gain is increased by": "奖励：经验增益增加",
    "Status:": "地位：",
    "The game inspired by": "游戏灵感来自",
    "The Level requirement is expensive.": "级别要求很昂贵。",
    "Tier": "等级",
    "times": "次",
    "Warning! Recommended size is 1920x1080! You may change zoom!": "警告！推荐尺寸为1920x1080！您可以更改缩放！",
    "You cannot buy any grass upgrades.": "您不能购买任何草升级。",
    "You cannot buy any Prestige Upgrades.": "您不能购买任何声望升级。",
    "You cannot tier up.": "你不能提升层级。",
    "You have grasshopped": "你有蚱蜢",
    "Prestige once to unlock.": "声望一次以解锁。",
    "Reach Level 30 to Prestige.": "达到声望等级 30。",
    "argh": "啊啊",
    "^0.5 to Grass, XP & PP gain.": "^0.5 草、经验 和 声望点 增益。",
    "Reach Level 5 to unlock.": "达到5级以解锁。",
    "doubled": "翻倍",
    "every": "每个",
    "Grass Value": "草值",
    "Grow Speed": "成长速度",
    "Increase experience (XP) gained by": "增加获得的经验（XP）",
    "Increase grass cap by": "增加草上限",
    "Increase grass cut range by": "将割草范围增加",
    "Increase Grass gain by": "增加草增益",
    "Increase grass grow speed by": "将草的生长速度提高",
    "levels.": "等级。",
    "More Grass": "更多的草",
    "per level.": "每级。",
    "per level. Base is 50.": "每级。 基数为 50。",
    "Range": "范围",
    "This effect is": "这个效果是",
    "XP": "经验值",
    "Grow Amount Perk": "生长数量天赋",
    "Grow Speed Perk": "成长速度天赋",
    "Increase the grass grow amount by": "将草的生长量增加",
    "Increase XP gain by": "增加经验增益",
    "per level multiplied by experience level.": "每个等级乘以经验等级。",
    "Range Perk": "范围天赋",
    "Value Perk": "价值天赋",
    "XP Perk": "经验天赋",
    "Cap Perk": "上限天赋",
    "Auto cuts grass every": "自动割草每",
    "Autocut": "自动割草",
    "seconds (-1s every level after the first).": "秒（第1级之后的每个等级 -1 秒）。",
    "Maxed": "最大",
    "Auto cuts grass is worth": "自动割草值得",
    "Autocut Amount": "自动割草数量",
    "Autocut Value": "自动割草值",
    "Grass Upgrade Autobuy": "草升级自动购买",
    "Increases auto cut amount by": "将自动割草数量增加",
    "more grass, XP & TP.": "更多的草，经验和TP。",
    "Perk Save P": "天赋保存 P",
    "Reach Tier 3 to unlock.": "达到第 3 层即可解锁。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    ". Unlock perk autobuyer upgrade.": ". 解锁 天赋 自动购买器 升级。",
    "Keep perks on Prestige.": "重置时保留天赋。",
    "You can now automatically buy Grass Upgrades.": "您现在可以自动购买草升级。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " XP/cut": " 经验/割",
    " TP/cut": " TP/割",
    " multiplier": " 乘数",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\(\+([\d\.]+)\/s\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+) XP$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) Grass$/, '你有 $1 草'],
    [/^You have (.+) Perk$/, '你有 $1 天赋'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^\(\+([\d\.]+)\/sec\)$/, '（\+$1\/秒）'],
    [/^([\d\.]+) seconds$/, '$1 秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) M Grass$/, '$1 M 草'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Perk$/, '$1 天赋'],
    [/^([\d\.,]+) Grass$/, '$1 草'],
    [/^([\d\.,]+) Grasshop$/, '$1 蚱蜢'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost to next 25: (.+) PP$/, '到下一个 25 的成本：$1 PP'],
    [/^Cost to next 25: (.+) Perk$/, '到下一个 25 的成本：$1 天赋'],
    [/^Cost to next 25: (.+) Grass$/, '到下一个 25 的成本：$1 草'],
    [/^Goal: Level (.+)$/, '目标：等级 $1'],
    [/^Goal: Tier (.+)$/, '目标：层级 $1'],
    [/^Cost: (.+) Grass$/, '成本：$1 草'],
    [/^Cost: (.+) Perk$/, '成本：$1 天赋'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);